name: Docker

on: 
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.7.1

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: executavel

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: leoparedes
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.10.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: leoparedes/go-ci:${{github.run_number}}

          
